### ISSUE TITLE
Unable to order some yarns

### ISSUE THREAD

**Issue by lizane** [UnionDesign/yarn-sites#105]
I'm currently testing as a wholesaler and under Yarns, for some reason any yarns after Tosca are not loading up when you try and place an order. http://staging.fleeceartist.flywheelsites.com/yarns/

It allows me to choose a hand dyed colour and reloads the page like it normally would when you add an new item but my cart remains the same after.

This is in the case of both Google Chrome and Safari.

**Comment by lizane** [comment]
You can still order yarns that are below Tosca through the Fast Order page if you know exactly what you want to order though there are also some quirks in it.. 
ex: I tried ordering Merino 2/6 in the colour Cedar and later in Beach House. However only the Beach House would load into the cart even after refreshing. Going back to the Fast Order page after browsing through other pages, I tried ordering the same thing Merino 2/6 in Cedar at the same time as another colour and it works! Was this a temporary glitch?

**Comment by UnionDesign** [comment]
Excellent catch!!!! This is fixed. Thank you!
