### ISSUE TITLE
Patterns: HTML in "Add to Cart" buttons

### ISSUE THREAD

**Issue by lizane** [UnionDesign/yarn-sites#108]
On the public staging site, the Fleece Artist patterns that are free downloads have a little glitch in the way the info is processed and shown. 
for example: on http://staging.fleeceartist.flywheelsites.com/product/lady-of-the-lake/

Same on the Lady of the Lake, Garter Stitch Jacket, Silky Thrums and Classic Thrums, etc; showing up on Safari and Chrome.
![screen shot 2015-08-10 at 3 44 10 pm](https://cloud.githubusercontent.com/assets/9930894/9180103/f5836322-3f76-11e5-9333-0423dec96aee.png)
![screen shot 2015-08-10 at 3 40 31 pm](https://cloud.githubusercontent.com/assets/9930894/9180113/fedcc3fa-3f76-11e5-8040-55f2107820b1.png)

**Comment by UnionDesign** [comment]
Unfortunately it looks like WooCommerce 2.4 (which just came out on Monday) doesn't allow HTML inside "Add to Cart" buttons anymore. So there's no way to style these buttons as designed anymore. The only thing I can do is remove the HTML and just have the button have a dash between "Add to Cart" and the details like "Free on FleeceArtist" all on one line and all in one font size, face and colour. Sorry.

**Comment by lizane** [comment]
please go ahead as per your reco.

**Comment by UnionDesign** [comment]
Done. If I hear back from WooComemece on a way to fix this... I will!
