### ISSUE TITLE
Feature Patterns: button placement

### ISSUE THREAD

**Issue by lizane** [UnionDesign/yarn-sites#109]
Not as urgent, but needs a fix nonetheless:
On Chrome the buttons are showing up cut in the featured patterns under some yarns on the public staging site like this: http://fleeceartist.com/product/sea-wool/ or this:
![screen shot 2015-08-10 at 2 26 59 pm](https://cloud.githubusercontent.com/assets/9930894/9180334/415c128e-3f78-11e5-84ba-10e8d2ce6f35.png)

They are showing up okay on Safari.

**Comment by UnionDesign** [comment]
Button alignment is fine on staging
