### ISSUE TITLE
Free HM patterns showing up with bar across

### ISSUE THREAD

**Issue by lizane** [UnionDesign/yarn-sites#113]
Similar to the free FA patterns, the info is showing up in a bar across the page. This is happening on both Safari and Chrome.
![screen shot 2015-08-11 at 9 41 41 am](https://cloud.githubusercontent.com/assets/9930894/9197767/98114334-400d-11e5-8659-566d6cd4ddbb.png)

**Comment by UnionDesign** [comment]
Duplicate issue
