### ISSUE TITLE
Free Pattern links

### ISSUE THREAD

**Issue by cameronjantzen** [UnionDesign/yarn-sites#117]
![screen shot 2015-08-31 at 4 21 15 pm](https://cloud.githubusercontent.com/assets/9700868/9588085/93e62a0a-4ffc-11e5-8cbd-c2e5b112f9ae.png)

Chrome and Safari - HM/FA patterns with free downloads - links whack.

**Comment by UnionDesign** [comment]
This WAS fixed and got broken again by a WooCommerce update. Fixed again.
