### ISSUE TITLE
"By Yarn" Filter not working

### ISSUE THREAD

**Issue by cameronjantzen** [UnionDesign/yarn-sites#118]
<img width="1650" alt="screen shot 2015-08-31 at 4 20 00 pm" src="https://cloud.githubusercontent.com/assets/9700868/9588102/b45ed250-4ffc-11e5-997e-8905d16e8d8c.png">

Safari + Chrome
when you click to sort by yarn, on HM + FA, no options appear.

**Comment by UnionDesign** [comment]
When I pushed the new code I cleared out the "Yarns" attributes and rebuilt them to make sure they were in sync. This accidentally probably deleted ALL Yarn attribute settings from all products on the site. I'll have to rollback the database from a backup.
