### ISSUE TITLE
Wholesaler Patterns Page formatting - URGENT

### ISSUE THREAD

**Issue by cameronjantzen** [UnionDesign/yarn-sites#119]
<img width="1650" alt="screen shot 2015-08-31 at 4 12 27 pm" src="https://cloud.githubusercontent.com/assets/9700868/9588146/fc10a20e-4ffc-11e5-88de-c8456227d799.png">

Safari + Chrome
Wholesaler Kits pages are whack.

**Comment by UnionDesign** [comment]
Some products had HTML in the content which was messing up the page. Removed the HTML. Appears to be fixed now.
