### ISSUE TITLE
Retailer List 

### ISSUE THREAD

**Issue by cameronjantzen** [UnionDesign/yarn-sites#28]
Wondering how the retailer list on the public facing site will populate - will this pull from the database of wholesalers with login accounts? That would be good.
We'll need a toggle to publish to none (lapsed customers), one or both public sites as some customers carry only one line. 

Let us know of any issues in terms of populating.

**Comment by UnionDesign** [comment]
Strongly recommend using the WP Store Locator plugin. The data will be properly structured so people can search by anything (zip, country, town... anything) plus they will get a zoomable map with driving directions and lots of other great features.

**Comment by UnionDesign** [comment]
Done
