### ISSUE TITLE
Error Messages with Pattern Downloads

### ISSUE THREAD

**Issue by Janamaria** [UnionDesign/yarn-sites#97]
Problems downloading Garterstitch jacket pattern and Storm Water Shawl. Ooops page comes up.

**Comment by Janamaria** [comment]
Problems with Fire Fox, Chrome, Exlporer and Safari on an iPad.  seems to be working with Safari on a desk top. seems to be widespread.

**Comment by UnionDesign** [comment]
"Oops" is a server thing. There were some other issues (asking for billing fields when it shouldn't) which I've fixed. It all seems good now.
